<?php

namespace CooperativeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MaraicherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaraicherRepository extends EntityRepository
{
}
