security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check         
            logout:
                path : fos_user_security_logout
                target : /
            anonymous:    true
    


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/production, role: ROLE_ADMIN }
        - { path: ^/produit, role: ROLE_ADMIN }
        - { path: ^/consomacteur, role: ROLE_ADMIN }
        - { path: ^/maraicher, role: ROLE_ADMIN }
        - { path: ^/membre, role: ROLE_ADMIN }
        - { path: ^/adresse, role: ROLE_ADMIN }

