maraicher:
    path:     /
    defaults: { _controller: "CooperativeBundle:Maraicher:index" }

maraicher_show:
    path:     /{id}/show
    defaults: { _controller: "CooperativeBundle:Maraicher:show" }

maraicher_new:
    path:     /new
    defaults: { _controller: "CooperativeBundle:Maraicher:new" }

maraicher_create:
    path:     /create
    defaults: { _controller: "CooperativeBundle:Maraicher:create" }
    requirements: { _method: post }

maraicher_edit:
    path:     /{id}/edit
    defaults: { _controller: "CooperativeBundle:Maraicher:edit" }

maraicher_update:
    path:     /{id}/update
    defaults: { _controller: "CooperativeBundle:Maraicher:update" }
    requirements: { _method: post|put }

maraicher_delete:
    path:     /{id}/delete
    defaults: { _controller: "CooperativeBundle:Maraicher:delete" }
    requirements: { _method: post|delete }
