produit:
    path:     /
    defaults: { _controller: "CooperativeBundle:Produit:index" }

produit_show:
    path:     /{id}/show
    defaults: { _controller: "CooperativeBundle:Produit:show" }

produit_new:
    path:     /new
    defaults: { _controller: "CooperativeBundle:Produit:new" }

produit_create:
    path:     /create
    defaults: { _controller: "CooperativeBundle:Produit:create" }
    requirements: { _method: post }

produit_edit:
    path:     /{id}/edit
    defaults: { _controller: "CooperativeBundle:Produit:edit" }

produit_update:
    path:     /{id}/update
    defaults: { _controller: "CooperativeBundle:Produit:update" }
    requirements: { _method: post|put }

produit_delete:
    path:     /{id}/delete
    defaults: { _controller: "CooperativeBundle:Produit:delete" }
    requirements: { _method: post|delete }
